### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by griffinlacek** [GregRednour/prj-rev-bwfs-dasmoto#6]
**Grade:** Meets Expectations

**Summary:** This project is a good start to your first deliverable code! It closely meets the spec and the code is mostly clean/free of any errors. One area of improvement is trying to wrap related HTML code with container divs, which will make styling and layout with CSS much easier in the future! Another is to try and reduce repeated styles in your CSS by targeting one selector like body instead of multiple individual elements.

As a further challenge, think about and try to change the page to have the item divs horizontally aligned instead of vertical aligned. There’s a few different ways to do this, but one way involves set widths and inline-block styling! This is a good resource for learning more: http://learnlayout.com/inline-block.html.

Good work!

**Comment by GregRednour** [comment]
Thanks for your review.  Agree completely.  Had placed <br/> in several locations, but did not match CodeCademy, so removed.  Ugh!  Also had div listed, but removed after I read somewhere it didn't really do anything.  So I appreciated your input.  Yes, I will definitely work on cleaner code, again, appreciate your input, by closing up blank lines and setting font-family for whole page.  Was not aware of AMP code. Thanks again.
